[project]
name = "personal-learning-research-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "imen", email = "imenchbili.03082004@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "docling>=2.132.0",
    "ipykernel>=7.4.0",
    "langchain>=1.4.3",
    "langchain-ollama>=1.1.0",
    "langchain-text-splitters>=1.1.3",
    "langgraph>=1.2.12",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "streamlit>=1.64.0",
]

[project.scripts]
personal-learning-research-agent = "personal_learning_research_agent:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
